#!/bin/sh

[ -z "$1" ] && exit

WALLS="$HOME/.config/hypr/.walls"

# Prompt the user for display number
printf "Set wallpaper for display: "
read DISPLAY

case "$DISPLAY" in
  1)
    TARGET="DP-1"
    IMAGE="$WALLS/dp1.png";;
  2)
    TARGET="DP-2"
    IMAGE="$WALLS/dp2.png";;
  *)
    exit;;
esac

# Unload relevant wallpaper to free RAM
hyprctl hyprpaper unload "$IMAGE"

# Save wallpaper to specific path to
# make them persistent between loads
convert "$1" "$IMAGE"

# Load wallpaper from current location
hyprctl hyprpaper preload "$IMAGE"
hyprctl hyprpaper wallpaper "$TARGET,$IMAGE"
